Repository ASEAN-Build-The-Earth/Merlion, pull requests merged in 2021-10, with the labels that each got.

#3 Create serveripstatussrv2.js
  commands/serveripstatussrv2.js
Labels: Hacktoberfest

#6 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: Hacktoberfest

#8 codeql-patch01
  .github/Readme.md
  .github/codeql/codeql-config.yml
  .github/workflows/codeql-analysis.yml
Labels: Hacktoberfest, bugfixes

#10 Hacktoberfest Guide for README.md
  README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#12 Project Pull Request Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: help wanted, Hacktoberfest

#15 New read me
  README.md
Labels: Hacktoberfest, hacktoberfest-accepted
